spring:
  application:
    name: "card-category"

  datasource:
    url: jdbc:postgresql://localhost:5432/card_category
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

app:
  security:
    username: ${USER}
    password: ${PASS}